### ISSUE TITLE
Texture Atlas on Things Rendered a Certain Way (A transparent layer?)

### ISSUE THREAD

**Issue by DarianLStephens** [DarkShadow44/CptsModdingLight#31] opened 2019-12-08 19:26 UTC
These objects are few and far between, but something about the interaction between them and Light Overhaul makes the texture atlas show up on them.
![2019-12-09_06 20 49](https://user-images.githubusercontent.com/15375876/70394797-74f0db80-1a4c-11ea-8aa1-611843b9454c.png)

This skeleton was punched; the atlas is shown red because that's the damage overlay.
I can only really theorize it has something to do with an object rendering a transparent layer on itself, if it's not a block?
I say 'not a block', since this scene renders fine:
![2019-12-09_06 23 28](https://user-images.githubusercontent.com/15375876/70394801-85a15180-1a4c-11ea-822b-1c99e7a817d1.png)

I wouldn't rule out the possibility of the mods being at fault for doing something wacky with rendering, though, since the similar BluePower mod's lamps render fine in-hand.

**Comment by DarkShadow44** [comment] 2019-12-08 21:33
Yeah I know that issue, that's #18. Though I should have been more explicit, thanks for the screenshots!

**Comment by DarianLStephens** [comment] 2019-12-09 04:52
Huh, I  could have sworn I tried punching other mobs and they seemed fine, but maybe I didn't look close enough.

**Comment by DarianLStephens** [comment] 2019-12-09 10:43
Yeah, it turns out all mobs have a broken damage overlay. Weird, I never noticed it before.

**Comment by DarkShadow44** [comment] 2019-12-29 19:55
Closing as dupe of #18, should be fixed in dev.

**Comment by DarianLStephens** [comment] 2019-12-30 00:25
Does that mean things like the lamp in these screenshots will render correctly while held?
That would be quite good news.

**Comment by DarkShadow44** [comment] 2019-12-30 00:35
Hm, seems like lamps are a different issue. Mobs work fine though.

**Comment by DarkShadow44** [comment] 2019-12-30 21:28
On hit animation worked in dev, but not with the released mod... Fixed that as of 2.1.2. Also added a rendering fix for handheld items, would you mind re-testing?

**Closed as completed** 2020-01-01 16:05 UTC
