### ISSUE TITLE
Unable to start game with Light Overhaul 2.0.0

### ISSUE THREAD

**Issue by DarianLStephens** [DarkShadow44/CptsModdingLight#25] opened 2019-12-07 09:37 UTC
Trying to launch Minecraft with MultiMC results in this error:
https://pastebin.com/r1dm77Zz
This is with literally just Forge and the mod.

I have not tried it with the vanilla Minecraft launcher.

**Comment by DarkShadow44** [comment] 2019-12-07 12:20
I never tested with MultiMC. It seems to be missing one of my dependencies...
But first, does the vanilla Minecraft launcher work?

**Comment by DarianLStephens** [comment] 2019-12-07 12:29
I haven't launched it in ages, but I'll give it a go.
I'm going to have to reset my password, because it's been so long that I was logged out on minecraft.net and I need to download a new launcher, since mine's apparently so outdated that it failed to update itself.

**Comment by DarianLStephens** [comment] 2019-12-08 15:34
I finally reset my password and tried the game with the vanilla launcher, but the same error occurred.

**Comment by DarkShadow44** [comment] 2019-12-08 16:57
Thanks for feedback, I just noticed what the problem is... I still had an old config where I passed "-noverify", that makes it work.
I needed to downgrade Mixin to properly solve the issue, and work around an issue in old Mixin.

It should work now, can you please test https://www.curseforge.com/minecraft/mc-mods/light-overhaul/files/2838454 once it's approved?
Fair warning though: This contains a lot of other updates too, it's not all working perfectly yet.

**Comment by DarianLStephens** [comment] 2019-12-08 17:57
The game didn't crash, and there's definitely colored light, but I get the feeling this is very much not how things should look:
![2019-12-09_04 49 16](https://user-images.githubusercontent.com/15375876/70393613-d494ba00-1a3f-11ea-8c78-83e6e7cdbe48.png)
Also, lights actually seem to darken the area during the day, and things like redstone torches don't give off noticeable color at night, but I don't know if these might be unavoidable side effects of trying to make colors visible during the day or if this is just unfinished:
![2019-12-09_04 52 55](https://user-images.githubusercontent.com/15375876/70393628-1f163680-1a40-11ea-96b5-9d8e028d750a.png)
Just so you know, I did test with a completely clean instance (Just Forge and Light Overhaul), with the same results.
A bit of a side-note, but have you looked in to what makes water think it's dark until it receives a block update? It really hampers the look of any area that's predominantly water.

I also saw that you were having difficulty filtering sunlight through blue stained glass, and it seems like it still has some slight problems towards to edges of it (Assuming it's not due to something unfinished). I placed some stained blue glass at the skylight of a desert temple and towards the walls on the bottom level, the light turned white.
I do have to say, though, that this stained glass light filtering is absolutely awesome!
![2019-12-09_05 01 51](https://user-images.githubusercontent.com/15375876/70393720-0e19f500-1a41-11ea-8c6d-5307223ca914.png)

**Comment by DarkShadow44** [comment] 2019-12-08 18:04
Yeah, I guess the sunlight changes broke something. I'll look into it the coming days, when I have the time. Thanks for the feedback! Mind opening separate bugreports for each of the issues you encountered?

**Comment by DarianLStephens** [comment] 2019-12-08 18:05
Good idea, I just get carried away with one comment.

**Comment by DarkShadow44** [comment] 2019-12-29 19:14
Since this is the one about not being able to start, closing.

**Closed as completed by DarkShadow44** 2019-12-29 19:14 UTC
