### ISSUE TITLE
Blue Filtered Sunlight turns white at the edges

### ISSUE THREAD

**Issue by DarianLStephens** [DarkShadow44/CptsModdingLight#26] opened 2019-12-08 18:08 UTC
After a while of normal blue light, it will suddenly turn white again, as demonstrated here:
![2019-12-09_05 07 37](https://user-images.githubusercontent.com/15375876/70393766-d6f81380-1a41-11ea-9d86-18acb844d34b.png)
Additionally, it looks as though smooth lighting isn't... oriented correctly for all angles? While it's a smooth line on the right in that image, directly in front of me it's jagged.

**Comment by DarkShadow44** [comment] 2019-12-08 18:26
I had the same issue when sideway filtering blue sunlight, maybe that one is similar. I'll look into it, thanks!
If you're curious, the problem is that I try to store 7 color channels in a single variable - that's sometimes a bit tight in these 32bits.

**Comment by DarianLStephens** [comment] 2019-12-08 18:28
I could see that being somewhat troublesome. I suppose a big reason for that is performance and save size concerns?

**Comment by DarkShadow44** [comment] 2019-12-08 18:32
Not really, the reason is that minecraft only ever accounted for 32bits of light. And unless I want to completely break compatibility, I am locked into this.

**Comment by DarianLStephens** [comment] 2019-12-08 18:33
I see. It seems a bit excessive for how lighting works in the original game, but I don't really know the requirements of that.

**Comment by DarkShadow44** [comment] 2021-10-30 15:46
1.7.10 version is out of date, the rework is written from scratch, so I close this bug.

**Closed as completed by DarkShadow44** 2021-10-30 15:46 UTC
