### ISSUE TITLE
Water Doesn't Light Properly in Worldgen

### ISSUE THREAD

**Issue by DarianLStephens** [DarkShadow44/CptsModdingLight#29] opened 2019-12-08 18:27 UTC
Water will be lit properly if it receives a block update (Usually, it requires a direct one), but otherwise will usually start unlit, with odd patches (Most commonly near an overhang or other terrain) where it's lit correctly:
![2019-12-09_05 24 10](https://user-images.githubusercontent.com/15375876/70393953-32c39c00-1a44-11ea-9b16-14a96a24bd58.png)
Small bodies are usually fine, with the occasional artifact:
![2019-12-09_05 23 27](https://user-images.githubusercontent.com/15375876/70393964-41aa4e80-1a44-11ea-9a3c-0196b839aa26.png)
Interestingly, looking at that first image, it looks as thought sunlight is hitting the shore and only spreading out from there, leaving the majority of the water unlit? I wonder if sunlight ignores or incorrectly interacts with water in some way?

Speaking of water, I don't suppose there are plans to make the new light color filtering work with water? It would be pretty neat to have light turn blue as it goes through water, though a minor concern would be how this would interact with biome water colors that differ extremely from the original...

**Comment by DarkShadow44** [comment] 2019-12-08 18:31
It wasn't planned, but feel free to open a feature request. Apart from differently colored water, it shouldn't be too hard to implement.
I mean, I can query the water color at position X, so I could theoretically calculate the new color for filtering in a certain way. But I need to try before I can tell.

**Comment by DarkShadow44** [comment] 2019-12-29 23:57
Should be fixed. Can you please test the newest version 2.1.1 (https://www.curseforge.com/minecraft/mc-mods/light-overhaul/files/2851549) and report back? I hope the performance didn't degrade too much.

**Comment by DarianLStephens** [comment] 2019-12-30 00:28
Re-lighting every chunk when it loads is an interesting idea, even outside of Colored Lights. A big concern I have is what happens on a server with a bunch of people moving around? Re-lighting each chunk then doesn't sound so great.
Theoretically, if you're actually fixing the lighting and it's not just client-side, you'd only need to do it once per chunk.
Although, if it is client-side, then the server performance issue is null.

**Comment by DarkShadow44** [comment] 2019-12-30 00:30
Light needs to be calculated on the server side, but only once a chunk is loaded/generated. Just moving around doesn't cause a recalculation.

**Comment by DarianLStephens** [comment] 2019-12-30 00:31
Sorry, I meant moving around as in travelling long distances. Whether generating new chunks or re-loading old ones.

**Comment by DarkShadow44** [comment] 2019-12-30 00:34
I'm not sure about the performance, but I needed to do something. If it gives problems, I'll rework it.

**Comment by DarianLStephens** [comment] 2019-12-30 00:41
Unfortunately, this does seem to have adversely affected performance.
There's noticeable stuttering when generating new chunks and travelling through old (Already-generated) chunks.
This is especially prominent when loading a world in Singleplayer; you can stay at 0 FPS for a while.

Although, when it re-does the lighting, it fixes the black spots in world-gen, so that's nice. Oddly enough, I did see some of that black lighting until I left and re-entered the chunks, so it didn't actually entire cure it.

**Comment by DarianLStephens** [comment] 2019-12-30 00:48
However, despite all that, it's very nice to be able to look out at a non-pure-black ocean:
![2019-12-30_11 47 52](https://user-images.githubusercontent.com/15375876/71564772-3b1a6e80-2afa-11ea-87da-89dff2db7e08.png)

**Comment by DarianLStephens** [comment] 2019-12-30 01:42
Although, upon further testing, I don't seem to be able to enter the Nether; the world never loads, and I'm stuck falling in a red void.

**Comment by DarkShadow44** [comment] 2019-12-30 02:05
Thanks for testing, I can confirm that the performance in the nether is terrible. It loads eventually, but that takes way too long. On the bright side, there are no render glitches. I need to find a balance there, without that lighting fix the nether is pretty buggy.

**Comment by DarianLStephens** [comment] 2019-12-30 03:26
Perhaps you could add a single bit of data to the chunks after your re-lighting happens? Set it to 1 when you're done, and that way each chunk only does it once, which should be enough to fix at least the vast majority of lighting glitches.
Although, thinking further, I'm not sure that would actually help with the Nether's loading time (Initially, at least), since you're probably only doing this once when the chunk is loaded.

**Comment by DarkShadow44** [comment] 2019-12-30 21:27
Water is a PITA. Just uploaded 2.1.2, this would both fix the performance issue and the water lightning issues. Turns out, water was simply implemented wrong - it doesn't take it's own light value for rendering, but the light from the block above it.
Please test and see if both water and the nether are fixed. Disclaimer: Existing worlds might be buggy, new should work just fine though.

**Comment by DarianLStephens** [comment] 2019-12-31 05:56
Not only has that fixed water in worldgen, it's also restored it to original brightness, rather than the odd slightly-darker water that I assumed was just a consequence of colored lights:
![2019-12-31_16 55 38](https://user-images.githubusercontent.com/15375876/71611614-67afb280-2bee-11ea-9efc-a4b892803055.png)
So, all in all, a massive success!

There are still some slightly odd spots where the lighting itself didn't work quite right, and ambient occlusion is still way too dark, but it's leagues better than before:
![2019-12-31_16 56 42](https://user-images.githubusercontent.com/15375876/71611645-afced500-2bee-11ea-95ac-4f0b89b330c0.png)
With those spots of light, maybe it's got something to do with chunk boundaries? It does seem a bit too coincidental that all the ones in this swamp that I checked fell on one side or the other of a chunk boundary.

**Comment by DarianLStephens** [comment] 2019-12-31 06:06
Although, the Nether is... a bit...
Well, it loads much faster, at least:
![2019-12-31_17 03 14](https://user-images.githubusercontent.com/15375876/71611726-98dcb280-2bef-11ea-90a2-8acfce1d2eae.png)
Interestingly, it almost looks like those weird lines are scanning across the chunks incredibly slowly:
![2019-12-31_17 03 29](https://user-images.githubusercontent.com/15375876/71611734-abef8280-2bef-11ea-9fa6-0492f1a5e071.png)
This one was taken a minute after the previous:
![2019-12-31_17 04 39](https://user-images.githubusercontent.com/15375876/71611735-adb94600-2bef-11ea-8b66-67c8e4210e6c.png)
![2019-12-31_17 05 07](https://user-images.githubusercontent.com/15375876/71611764-dc372100-2bef-11ea-9e58-69fcd9379eaa.png)
![2019-12-31_17 05 38](https://user-images.githubusercontent.com/15375876/71611766-dccfb780-2bef-11ea-96eb-ff74add703fa.png)

**Comment by DarianLStephens** [comment] 2019-12-31 06:14
Also interestingly, although lava falls now seem to be properly lit, the topmost block touching another block isn't:
![2019-12-31_17 09 43](https://user-images.githubusercontent.com/15375876/71611845-71d2b080-2bf0-11ea-839c-83fb7105c12c.png)
It's not a lighting glitch, either, since I've tried updating them to no avail. It will also turn pure black if you put a block next to it period, so it's likely something to do with how the liquid renders:
![2019-12-31_17 12 05](https://user-images.githubusercontent.com/15375876/71611889-b2322e80-2bf0-11ea-9981-8d82e02245a3.png)
![2019-12-31_17 12 19](https://user-images.githubusercontent.com/15375876/71611891-b9593c80-2bf0-11ea-866b-e117cb8c8ac3.png)
Additionally, lighting glitches in general seem to be less common. I have yet to see a 'dark fire' (Fire that won't emit light without being updated), and the vast majority of the colored glowstone seems to all be lit properly, whereas in previous versions they'd be so commonplace I'd practically have to ignore them or go mad.

**Comment by DarkShadow44** [comment] 2019-12-31 14:46
Thanks for testing, will take a look at it the next year.

**Comment by DarianLStephens** [comment] 2019-12-31 14:56
Fair enough, I'll look forward to some more info next decade.

**Comment by DarkShadow44** [comment] 2021-10-30 15:41
1.7.10 version is out of date, the rework is written from scratch, so I close this bug.

**Closed as completed by DarkShadow44** 2021-10-30 15:41 UTC
