### ISSUE TITLE
Hardcore Darkness Compatibility Lost

### ISSUE THREAD

**Issue by DarianLStephens** [DarkShadow44/CptsModdingLight#36] opened 2019-12-13 17:43 UTC
Before the big Light Overhaul release, you claimed to add Hardcore Darkness compatibility (In reality, you seemed to just remove the omnipresent ambient light by default; moon phases and things from Hardcore Darkness didn't work, either), but the mod now does nothing in the current version of Light Overhaul.

**Comment by DarkShadow44** [comment] 2019-12-13 17:50
The new update seems to have broken that, thanks for reporting. I'll look into it - probably needs a rework with the new sunlight. Maybe I'll have to add a hardcore darkness mode myself.

**Comment by DarianLStephens** [comment] 2019-12-13 20:28
> Maybe I'll have to add a hardcore darkness mode myself

I thought that's what you did last time? I didn't see any difference regardless of whether or not Hardcore Darkness was installed; it was just permanently pitch-black in darkness even with only Colored Lights.
I'm guessing the mod can't really do its changes since the lighting system has been pretty well re-written here, so beyond doing another big rewrite (Or Hardcore Darkness releasing an update), I think the only way to really do it is to implement the mod (Or something similar) directly in to this mod, including the pitch-black nether and 'night light is dependent on moon phase' option.
I'm not sure how the blue moonlight worked, but I found it beautiful. I don't suppose the colored lighting engine here would help with implementing that, since you'd likely need to update every block in the world if you try to use the color system.

**Comment by DarkShadow44** [comment] 2019-12-14 11:59
> I thought that's what you did last time

Only partially - the problem is that it now uses shaders instead of the regular lightmap, so other mods can't change much there.

> I'm not sure how the blue moonlight worked, but I found it beautiful. I don't suppose the colored lighting engine here would help with implementing that, since you'd likely need to update every block in the world if you try to use the color system.

That's not a problem - we can set sunlight color anytime without problems.

**Comment by DarianLStephens** [comment] 2019-12-14 15:11
Oh, here I thought you still had to update every block when you changed sunlight color.
I assume when you say 'sunlight', you mean any light coming from the sky, which would include moonlight (Which is probably technically sunlight with the color changed? Or rather, there's no distinction, it's all the same, just changed based on the time of day).

**Comment by DarkShadow44** [comment] 2021-10-30 15:41
1.7.10 version is out of date, the rework is written from scratch, so I close this bug.

**Closed as completed by DarkShadow44** 2021-10-30 15:41 UTC
